spring.application.name=solchi

spring.datasource.url=jdbc:postgresql://localhost:5433/solchi
spring.datasource.username=solchi
spring.datasource.password=solchi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
