spring.application.name=solchi

spring.datasource.url=jdbc:postgresql://localhost:5433/solchi
spring.datasource.username=solchi
spring.datasource.password=solchi

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
